version: "3"

services:
  django:
    build: ..
    container_name: django
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - sqlite

  sqlite:
    image: nouchka/sqlite3
    container_name: sqlite
    stdin_open: true
    tty: true
    volumes:
      - ./db:/root/db/

#  pgdb:
#    image: postgres
#    environment:
#      - POSTGRES_DB = postgres
#      - POSTGRES_USER = postgres
#      - POSTGRES_PASSWORD = postgres
#    container_name: pgdb
#    volumes:
#      - pgdbdata:/var/lib.postgresql/data/